"""crk6_1 -- 2D-LATTICE PERIODIC CONTINUATION (data-dependent period vector, opset 10).

The input is the TOP rows of a W x W square; the bottom rows are missing.  The
grid is generated by a single translation symmetry: there is a lattice vector
(dr, dc) with dr >= 1 such that grid[r, c] == grid[r-dr, c-dc] wherever both are
inside the input.  The output completes the square by extrapolating that vector
downward (vertical periods give dc = 0; diagonal "staircase" patterns give dc != 0).

The vector is NOT fixed across the task, so a static graph cannot bake it in.  It
is recovered AT INFERENCE TIME:

  * Detection: for each static candidate (dr, dc) in priority order
        dr = 1..KMAX, dc in [0, +1, -1, +2, -2]
    measure the colour-autocorrelation mismatch over the real overlap; the chosen
    vector is the FIRST candidate with zero mismatch AND non-empty overlap.  The
    "first valid" is realised with a cumulative one-hot, so (dr*, dc*) pop out as
    two [1,1] floats.

  * Fill: a residue class repeats every (dr, dc), so OR-ing the one-hot content
    with all of its diagonal shifts k*(dr, dc) (k = +/-1,2,4,8 via 4 doubling
    steps) recovers the value at every cell whose class has a visible member.  A
    diagonal shift is S_row @ F @ S_col with the two 30x30 permutation matrices
    built on the fly from the data-dependent (dr*, dc*).

  * Crop & background: the answer is a W x W square (W = number of real columns,
    data-dependent); cells outside it must be padding and any in-square cell with
    no colour is routed to channel 0 (background).

Detection mirrors the ONNX semantics EXACTLY and only emits when the
reconstruction reproduces EVERY train+test+arc-gen pair.
"""
from __future__ import annotations

import numpy as np
import onnx
from onnx import helper as oh

from ng_utils_shim import (
    DATA_TYPE, GRID_SHAPE, IR_VERSION, OPSET_IMPORTS, CHANNELS, HEIGHT, WIDTH,
)

INT64 = onnx.TensorProto.INT64
F = DATA_TYPE
G = HEIGHT  # 30
KMAX = 7
DC_ORDER = [0, 1, -1, 2, -2]
CANDS = [(dr, dc) for dr in range(1, KMAX + 1) for dc in DC_ORDER]
NDBL = 4  # doubling steps -> covers +/- (2^NDBL - 1) multiples


# --------------------------------------------------------------------------- #
# tiny graph accumulator                                                       #
# --------------------------------------------------------------------------- #
class _G:
    def __init__(self):
        self.nodes = []
        self.inits = []
        self._k = 0

    def nm(self, p="t"):
        self._k += 1
        return f"{p}{self._k}"

    def f(self, dims, vals):
        n = self.nm("c")
        self.inits.append(oh.make_tensor(n, F, list(dims),
                                         [float(v) for v in np.asarray(vals, np.float32).ravel()]))
        return n

    def i64(self, vals):
        n = self.nm("i")
        self.inits.append(oh.make_tensor(n, INT64, [len(vals)], [int(v) for v in vals]))
        return n

    def nd(self, op, ins, out=None, **a):
        out = out or self.nm()
        self.nodes.append(oh.make_node(op, list(ins), [out], **a))
        return out


def _model(g):
    x = oh.make_tensor_value_info("input", F, GRID_SHAPE)
    y = oh.make_tensor_value_info("output", F, GRID_SHAPE)
    graph = oh.make_graph(g.nodes, "g", [x], [y], g.inits)
    return oh.make_model(graph, ir_version=IR_VERSION, opset_imports=OPSET_IMPORTS)


def _shift2(g, t, dr, dc):
    """up-left shift of [1,K,30,30] tensor: out[r,c] = t[r+dr, c+dc], zero fill.
    dr >= 0; dc any sign (static)."""
    cur = t
    if dr > 0:
        cur = g.nd("Slice", [cur, g.i64([dr]), g.i64([G]), g.i64([2])])
        cur = g.nd("Pad", [cur], mode="constant", value=0.0,
                   pads=[0, 0, 0, 0, 0, 0, dr, 0])
    if dc > 0:
        cur = g.nd("Slice", [cur, g.i64([dc]), g.i64([G]), g.i64([3])])
        cur = g.nd("Pad", [cur], mode="constant", value=0.0,
                   pads=[0, 0, 0, 0, 0, 0, 0, dc])
    elif dc < 0:
        e = -dc
        cur = g.nd("Slice", [cur, g.i64([0]), g.i64([G - e]), g.i64([3])])
        cur = g.nd("Pad", [cur], mode="constant", value=0.0,
                   pads=[0, 0, 0, e, 0, 0, 0, 0])
    return cur


def build():
    g = _G()
    half = g.f([1, 1], [0.5])
    halfc = g.f([1, 1, 1, 1], [0.5])
    one11 = g.f([1, 1], [1.0])

    # colour index plane & real mask
    colvec = g.f([1, CHANNELS, 1, 1], list(range(CHANNELS)))
    color = g.nd("ReduceSum", [g.nd("Mul", ["input", colvec])], axes=[1], keepdims=1)  # [1,1,30,30]
    realmask = g.nd("ReduceSum", ["input"], axes=[1], keepdims=1)                       # [1,1,30,30]
    known = realmask

    # ---- detection: first valid (dr,dc) ----
    dr_star = None
    dc_star = None
    remaining = None
    for (dr, dc) in CANDS:
        shK = _shift2(g, known, dr, dc)
        shC = _shift2(g, color, dr, dc)
        both = g.nd("Mul", [known, shK])
        diff = g.nd("Abs", [g.nd("Sub", [color, shC])])
        mism = g.nd("Cast", [g.nd("Greater", [diff, halfc])], to=F)
        prod = g.nd("Mul", [both, mism])
        score = g.nd("ReduceSum", [prod], axes=[2, 3], keepdims=0)     # [1,1]
        overlap = g.nd("ReduceSum", [both], axes=[2, 3], keepdims=0)   # [1,1]
        score0 = g.nd("Cast", [g.nd("Less", [score, half])], to=F)
        ovpos = g.nd("Cast", [g.nd("Greater", [overlap, half])], to=F)
        valid = g.nd("Mul", [score0, ovpos])                          # [1,1]
        if remaining is None:
            gate = valid
            remaining = g.nd("Sub", [one11, valid])
        else:
            gate = g.nd("Mul", [valid, remaining])
            remaining = g.nd("Mul", [remaining, g.nd("Sub", [one11, valid])])
        cdr = g.nd("Mul", [gate, g.f([1, 1], [float(dr)])])
        cdc = g.nd("Mul", [gate, g.f([1, 1], [float(dc)])])
        dr_star = cdr if dr_star is None else g.nd("Add", [dr_star, cdr])
        dc_star = cdc if dc_star is None else g.nd("Add", [dc_star, cdc])

    # ---- fill: diagonal doubling-OR ----
    rowidx = g.f([G, 1], list(range(G)))
    colidx = g.f([1, G], list(range(G)))
    t_row = g.nd("Sub", [rowidx, colidx])   # [30,30] i-j  (row shift via left-mult)
    t_col = g.nd("Sub", [colidx, rowidx])   # [30,30] j-i  (col shift via right-mult)

    cur = "input"
    for k in range(NDBL):
        if k == 0:
            Dr, Dc = dr_star, dc_star
        else:
            f2 = g.f([1, 1], [float(2 ** k)])
            Dr = g.nd("Mul", [dr_star, f2])
            Dc = g.nd("Mul", [dc_star, f2])
        s_down = g.nd("Cast", [g.nd("Less", [g.nd("Abs", [g.nd("Sub", [t_row, Dr])]), half])], to=F)
        s_up = g.nd("Cast", [g.nd("Less", [g.nd("Abs", [g.nd("Add", [t_row, Dr])]), half])], to=F)
        s_right = g.nd("Cast", [g.nd("Less", [g.nd("Abs", [g.nd("Sub", [t_col, Dc])]), half])], to=F)
        s_left = g.nd("Cast", [g.nd("Less", [g.nd("Abs", [g.nd("Add", [t_col, Dc])]), half])], to=F)
        pos = g.nd("MatMul", [g.nd("MatMul", [s_down, cur]), s_right])   # down-right
        neg = g.nd("MatMul", [g.nd("MatMul", [s_up, cur]), s_left])       # up-left
        cur = g.nd("Max", [cur, pos, neg])

    # ---- crop to W x W (W = number of real columns) ----
    colpresent = g.nd("ReduceMax", [realmask], axes=[2], keepdims=1)     # [1,1,1,30]
    W = g.nd("ReduceSum", [colpresent], axes=[3], keepdims=1)            # [1,1,1,1]
    colidx_p = g.f([1, 1, 1, G], list(range(G)))
    rowidx_p = g.f([1, 1, G, 1], list(range(G)))
    colcrop = g.nd("Cast", [g.nd("Less", [colidx_p, W])], to=F)          # [1,1,1,30]
    rowcrop = g.nd("Cast", [g.nd("Less", [rowidx_p, W])], to=F)          # [1,1,30,1]
    cropmask = g.nd("Mul", [colcrop, rowcrop])                           # [1,1,30,30]
    cur = g.nd("Mul", [cur, cropmask])

    # ---- background routing: in-square cells with no colour -> channel 0 ----
    mask_no0 = g.f([1, CHANNELS, 1, 1], [0.0] + [1.0] * (CHANNELS - 1))
    cur_no0 = g.nd("Mul", [cur, mask_no0])
    colored = g.nd("ReduceSum", [cur_no0], axes=[1], keepdims=1)         # [1,1,30,30]
    colbin = g.nd("Cast", [g.nd("Greater", [colored, halfc])], to=F)
    one_c = g.f([1, 1, 1, 1], [1.0])
    newch0 = g.nd("Mul", [cropmask, g.nd("Sub", [one_c, colbin])])       # [1,1,30,30]
    e0 = g.f([1, CHANNELS, 1, 1], [1.0] + [0.0] * (CHANNELS - 1))
    g.nd("Add", [cur_no0, g.nd("Mul", [newch0, e0])], "output")
    return _model(g)


# --------------------------------------------------------------------------- #
# numpy reference (mirrors the ONNX semantics EXACTLY)                          #
# --------------------------------------------------------------------------- #
def _onehot(a):
    H, W = a.shape
    X = np.zeros((CHANNELS, G, G), np.float32)
    for c in range(CHANNELS):
        X[c, :H, :W] = (a == c)
    return X


def _shift_ul(t, dr, dc):
    out = np.zeros_like(t)
    tmp = np.zeros_like(t)
    if dr < G:
        if dr > 0:
            tmp[..., 0:G - dr, :] = t[..., dr:G, :]
        else:
            tmp = t.copy()
    else:
        return out
    if dc == 0:
        out = tmp
    elif dc > 0 and dc < G:
        out[..., :, 0:G - dc] = tmp[..., :, dc:G]
    elif dc < 0 and -dc < G:
        e = -dc
        out[..., :, e:G] = tmp[..., :, 0:G - e]
    return out


def _shift_dr(T, dr, dc):
    out = np.zeros_like(T)
    tmp = np.zeros_like(T)
    if abs(dr) >= G or abs(dc) >= G:
        if dr == 0 and dc == 0:
            return T.copy()
    if dr > 0:
        tmp[..., dr:G, :] = T[..., 0:G - dr, :]
    elif dr < 0:
        tmp[..., 0:G + dr, :] = T[..., -dr:G, :]
    else:
        tmp = T.copy()
    if dc == 0:
        out = tmp
    elif dc > 0:
        out[..., :, dc:G] = tmp[..., :, 0:G - dc]
    else:
        e = -dc
        out[..., :, 0:G - e] = tmp[..., :, e:G]
    return out


def _sim(a):
    X = _onehot(a)
    real = X.sum(0)
    color = sum(c * X[c] for c in range(CHANNELS))
    known = real
    dr_star = 0.0
    dc_star = 0.0
    chosen = False
    for (dr, dc) in CANDS:
        shK = _shift_ul(known, dr, dc)
        shC = _shift_ul(color, dr, dc)
        both = known * shK
        mism = (np.abs(color - shC) > 0.5).astype(np.float32)
        score = float((both * mism).sum())
        overlap = float(both.sum())
        if (not chosen) and score < 0.5 and overlap > 0.5:
            dr_star, dc_star, chosen = dr, dc, True
    cur = X.copy()
    for k in range(NDBL):
        Dr = int(round(dr_star * (2 ** k)))
        Dc = int(round(dc_star * (2 ** k)))
        pos = _shift_dr(cur, Dr, Dc)
        neg = _shift_ul(cur, Dr, Dc)
        cur = np.maximum(np.maximum(cur, pos), neg)
    W = int(round(real.max(axis=0).sum())) if real.any() else 0
    crop = np.zeros((G, G), np.float32)
    crop[:W, :W] = 1.0
    cur = cur * crop[None]
    colored = (cur[1:] > 0.5).any(0).astype(np.float32)
    cur[0] = crop * (1.0 - colored)
    return cur


def _sim_grid(a):
    out = _sim(a)
    sel = out > 0.5
    cnt = sel.sum(0)
    W = a.shape[1]
    if (cnt[:W, :W] != 1).any():
        return None
    if cnt.sum() != W * W:
        return None
    return np.argmax(sel, axis=0)


# --------------------------------------------------------------------------- #
# detection / entry point                                                      #
# --------------------------------------------------------------------------- #
def _pairs(ex, splits):
    out = []
    for s in splits:
        for e in ex.get(s, []):
            a = np.array(e["input"], int)
            b = np.array(e["output"], int)
            if a.ndim != 2 or b.ndim != 2 or a.size == 0 or b.size == 0:
                continue
            if max(a.shape) > G or max(b.shape) > G:
                continue
            out.append((a, b))
    return out


def candidates(ex):
    det = _pairs(ex, ("train", "test"))
    allp = _pairs(ex, ("train", "test", "arc-gen"))
    if not det or not allp:
        return []
    # require: output is a square, larger-or-equal than input height, same width
    for a, b in allp:
        H, W = a.shape
        Ho, Wo = b.shape
        if not (Ho == Wo == W and Ho >= H):
            return []
    if all(np.array_equal(a, b) for a, b in allp):
        return []

    def ok(plist):
        for a, b in plist:
            pred = _sim_grid(a)
            if pred is None:
                return False
            Ho, Wo = b.shape
            if not np.array_equal(pred[:Ho, :Wo], b):
                return False
        return True

    if not ok(det) or not ok(allp):
        return []

    try:
        model = build()
        onnx.checker.check_model(model, full_check=True)
    except Exception:
        return []
    return [("crk6_1_lattice", model)]
