"""family_vc4_1 — RE-EXAMINATION of task255 (a64e4611) and task363 (e5062a87).

Mandate: the "non-geometric tie-break" verdict was proven wrong for task233 (its
tie-break was a fixed canonical D4 order). Re-run the same protocol here: collect the
divergent cells vs the NeuroGolf/JSON data and try to reproduce them with a canonical or
geometric tie-break that keeps ALL agreeing examples exact. Result below. Both remain
UNSOLVABLE, but for a DIFFERENT and now-PROVEN reason than "some fuzzy tie-break": the
task JSON is internally INCONSISTENT — the hand-authored train examples follow a rule the
verifier-generated arc-gen examples contradict. No deterministic function can satisfy both,
so the grader's "exact on train+test+arc-gen" gate cannot be met by any model. This family
emits nothing (documented negative result; no regression risk — both tasks score 0 today).

=====================================================================================
task363 (verify_e5062a87) — PROVEN unsolvable (data contradiction)
=====================================================================================
Rule (verifier): motif = normalize(ofcolor(I, leastcolor)). Stamp the motif (color =
leastcolor) at EVERY location whose footprint is entirely over background 0. "stamp-all".
stamp-all is EXACT on 263/265 (all 261 arc-gen + test), fails only train[0], train[1].

I re-derived the hand-authored rule and it is NOT a fuzzy tie-break — it is well-defined:
  - train[0] (2-D diamond motif): overlapping occurrences resolved by FARTHEST-FIRST
    greedy (process occ by decreasing manhattan dist from the motif origin, stamp if it
    does not collide with an already-stamped cell). This reproduces train[0] EXACTLY and,
    applied alone ("far"), it is exact on 264/265 (only train[1] wrong) — strictly better
    than stamp-all.
  - train[1] (1-D horizontal line motif): keep only the occurrence collinear with the
    motif's own row; drop the off-row occurrence (1,3). "axis-restricted extension".

The refined single rule
    if a 1-D motif has an on-axis occurrence -> keep only on-axis (then far-greedy)
    else -> far-greedy over all occurrences
passes ALL of train+test and misses only 2 arc-gen (idx 96, 248). So train[2]-style local
reasoning is NOT the blocker; the blocker is a hard contradiction inside arc-gen itself:

  DIRECT CONTRADICTION (both are horizontal 4-cell line motifs; both HAVE an on-row occ):
    train[1]  : origin (5,1); occ = {(1,3) off-row, (5,6) on-row};
                output keeps ONLY (5,6) -> off-row occurrence (1,3) MUST be dropped.
    arc-gen 96: origin (1,6); occ = {(1,1) on-row, (2,0),(4,5),(7,6) all off-row};
                output keeps ALL FOUR -> the off-row occurrences MUST be kept.
  (arc-gen 11 is a second witness: horizontal 4-motif, its ONLY occ (3,0) is off-row and is
   kept, so an "always axis-restrict" rule also fails.)

Identical local situation, opposite required output. No deterministic function of the input
can both drop and keep an off-row occurrence in the on-row-present case. The arc-gen set was
generated by the stamp-all verifier; the two train examples are the original hand-authored
ARC pair following the true "axis-restricted / farthest-greedy" rule. The two rule families
are mutually exclusive on this data. => task363 is unsolvable exactly; no candidate can pass
the train+test gate AND arc-gen simultaneously. Best faithful numpy rule: "far" (264/265).

=====================================================================================
task255 (verify_a64e4611) — unsolvable (non-local stub removal, contradicts arc-gen)
=====================================================================================
verify_a64e4611 (empty 3x14 / 14x3 window occurrence-stamp -> border frame -> tip erosion,
rot90 chain x8, final trim) is EXACT vs JSON on 264/265. The ONLY divergence is train[2],
6 cells = two thin 1-wide x 3-long "fingers" the verifier leaves on the 3-cross:
    verifier=3, json=0 at (16..18, 16)  [finger sticking right off the vertical band]
                    and (19..21, 0)      [finger sticking down off the horizontal band].
The JSON straightens the cross to clean maximal rectangles and removes both fingers.

This is NOT a tie-break / canonical-order question at all — there is no ambiguous choice to
order; it is which cells get filled, and the verifier over-fills by 6 on this one input.
Re-tested every geometric / canonical removal that could reproduce train[2]:
  - 3x3 morphological opening of the 3-mask: removes the fingers but rounds legit band
    corners -> breaks 195/265.
  - run-length "keep iff horizontal-run>=L AND vertical-run>=L" for L=2..8: the two fingers
    (finger A vertical-run 3; finger B horizontal-run 1) die, but arc-gen contains many
    LEGITIMATE thin (<=3) 3-bands that are identical locally and also die -> breaks 132..240.
Finger A needs a length>=4 vertical opening; finger B needs a length>=2 horizontal opening;
no single local structuring element removes both without killing arc-gen's thin bands. The
removal is a global maximal-empty-rectangle / component-shape property ("this thin appendage
is not supported by any maximal rectangle"), which is (a) not reproducible by any local rule
exact on all 265, and (b) not expressible as a cheap static opset-10 graph. Additionally the
verifier mechanism itself (14-long empty-window occurrences + frame + iterated erosion) has
no cheap static-ONNX form. train[2] is in the TRAIN set, so the candidate/grader gate cannot
be met. => task255 unsolvable exactly.

Divergent cells recap (report these):
  task255 train[2]: (16,16),(17,16),(18,16),(19,0),(20,0),(21,0)  verifier=3 json=0.
  task363 train[1]: off-row occ (1,3) -> footprint (1,3),(1,4),(1,5),(1,6) json leaves 0,
                    contradicted by arc-gen[96] which keeps the analogous off-row footprints.
"""


def candidates(examples):
    return []
